# Generated by Django 3.2.5 on 2021-07-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_telegram_id', models.CharField(max_length=15)),
                ('client_telegram_nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('client_phone_number', models.CharField(blank=True, max_length=14, null=True)),
                ('master', models.ManyToManyField(blank=True, related_name='clients', to='master.Master')),
            ],
        ),
    ]
