# Generated by Django 3.2.5 on 2021-08-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_telegram_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
