# Generated by Django 3.2.5 on 2021-07-25 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20210725_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifycodes',
            old_name='user',
            new_name='master',
        ),
    ]
