# Generated by Django 3.2.5 on 2021-08-04 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('master', '0003_rename_user_verifycodes_master'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField()),
                ('datetime_slot', models.DateTimeField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='schedule',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='order.order'),
        ),
        migrations.CreateModel(
            name='ArchiveSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField()),
                ('datetime_slot', models.DateTimeField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master.master')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.order')),
            ],
        ),
    ]
