# Generated by Django 3.2.5 on 2021-07-21 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='client.client')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='master.master')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicservice', to='master.service')),
            ],
        ),
    ]
